# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/router/Desktop/vscode_workplace/boost_asio/posix_time

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/router/Desktop/vscode_workplace/boost_asio/posix_time

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Desktop/vscode_workplace/boost_asio/posix_time/CMakeFiles /home/router/Desktop/vscode_workplace/boost_asio/posix_time/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Desktop/vscode_workplace/boost_asio/posix_time/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named daytime

# Build rule for target.
daytime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daytime
.PHONY : daytime

# fast build rule for target.
daytime/fast:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/build
.PHONY : daytime/fast

#=============================================================================
# Target rules for targets named multithread

# Build rule for target.
multithread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multithread
.PHONY : multithread

# fast build rule for target.
multithread/fast:
	$(MAKE) -f CMakeFiles/multithread.dir/build.make CMakeFiles/multithread.dir/build
.PHONY : multithread/fast

#=============================================================================
# Target rules for targets named bind

# Build rule for target.
bind: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bind
.PHONY : bind

# fast build rule for target.
bind/fast:
	$(MAKE) -f CMakeFiles/bind.dir/build.make CMakeFiles/bind.dir/build
.PHONY : bind/fast

#=============================================================================
# Target rules for targets named posix_time

# Build rule for target.
posix_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 posix_time
.PHONY : posix_time

# fast build rule for target.
posix_time/fast:
	$(MAKE) -f CMakeFiles/posix_time.dir/build.make CMakeFiles/posix_time.dir/build
.PHONY : posix_time/fast

#=============================================================================
# Target rules for targets named test_1

# Build rule for target.
test_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_1
.PHONY : test_1

# fast build rule for target.
test_1/fast:
	$(MAKE) -f CMakeFiles/test_1.dir/build.make CMakeFiles/test_1.dir/build
.PHONY : test_1/fast

#=============================================================================
# Target rules for targets named daytimeserver

# Build rule for target.
daytimeserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daytimeserver
.PHONY : daytimeserver

# fast build rule for target.
daytimeserver/fast:
	$(MAKE) -f CMakeFiles/daytimeserver.dir/build.make CMakeFiles/daytimeserver.dir/build
.PHONY : daytimeserver/fast

#=============================================================================
# Target rules for targets named asyncdaytimeserver

# Build rule for target.
asyncdaytimeserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asyncdaytimeserver
.PHONY : asyncdaytimeserver

# fast build rule for target.
asyncdaytimeserver/fast:
	$(MAKE) -f CMakeFiles/asyncdaytimeserver.dir/build.make CMakeFiles/asyncdaytimeserver.dir/build
.PHONY : asyncdaytimeserver/fast

#=============================================================================
# Target rules for targets named printer

# Build rule for target.
printer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 printer
.PHONY : printer

# fast build rule for target.
printer/fast:
	$(MAKE) -f CMakeFiles/printer.dir/build.make CMakeFiles/printer.dir/build
.PHONY : printer/fast

#=============================================================================
# Target rules for targets named echoserver

# Build rule for target.
echoserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echoserver
.PHONY : echoserver

# fast build rule for target.
echoserver/fast:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/build
.PHONY : echoserver/fast

#=============================================================================
# Target rules for targets named echoclient

# Build rule for target.
echoclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echoclient
.PHONY : echoclient

# fast build rule for target.
echoclient/fast:
	$(MAKE) -f CMakeFiles/echoclient.dir/build.make CMakeFiles/echoclient.dir/build
.PHONY : echoclient/fast

asyncdaytimeserver.o: asyncdaytimeserver.cc.o

.PHONY : asyncdaytimeserver.o

# target to build an object file
asyncdaytimeserver.cc.o:
	$(MAKE) -f CMakeFiles/asyncdaytimeserver.dir/build.make CMakeFiles/asyncdaytimeserver.dir/asyncdaytimeserver.cc.o
.PHONY : asyncdaytimeserver.cc.o

asyncdaytimeserver.i: asyncdaytimeserver.cc.i

.PHONY : asyncdaytimeserver.i

# target to preprocess a source file
asyncdaytimeserver.cc.i:
	$(MAKE) -f CMakeFiles/asyncdaytimeserver.dir/build.make CMakeFiles/asyncdaytimeserver.dir/asyncdaytimeserver.cc.i
.PHONY : asyncdaytimeserver.cc.i

asyncdaytimeserver.s: asyncdaytimeserver.cc.s

.PHONY : asyncdaytimeserver.s

# target to generate assembly for a file
asyncdaytimeserver.cc.s:
	$(MAKE) -f CMakeFiles/asyncdaytimeserver.dir/build.make CMakeFiles/asyncdaytimeserver.dir/asyncdaytimeserver.cc.s
.PHONY : asyncdaytimeserver.cc.s

bind.o: bind.cc.o

.PHONY : bind.o

# target to build an object file
bind.cc.o:
	$(MAKE) -f CMakeFiles/bind.dir/build.make CMakeFiles/bind.dir/bind.cc.o
.PHONY : bind.cc.o

bind.i: bind.cc.i

.PHONY : bind.i

# target to preprocess a source file
bind.cc.i:
	$(MAKE) -f CMakeFiles/bind.dir/build.make CMakeFiles/bind.dir/bind.cc.i
.PHONY : bind.cc.i

bind.s: bind.cc.s

.PHONY : bind.s

# target to generate assembly for a file
bind.cc.s:
	$(MAKE) -f CMakeFiles/bind.dir/build.make CMakeFiles/bind.dir/bind.cc.s
.PHONY : bind.cc.s

daytime.o: daytime.cc.o

.PHONY : daytime.o

# target to build an object file
daytime.cc.o:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.cc.o
.PHONY : daytime.cc.o

daytime.i: daytime.cc.i

.PHONY : daytime.i

# target to preprocess a source file
daytime.cc.i:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.cc.i
.PHONY : daytime.cc.i

daytime.s: daytime.cc.s

.PHONY : daytime.s

# target to generate assembly for a file
daytime.cc.s:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.cc.s
.PHONY : daytime.cc.s

daytimeserver.o: daytimeserver.cc.o

.PHONY : daytimeserver.o

# target to build an object file
daytimeserver.cc.o:
	$(MAKE) -f CMakeFiles/daytimeserver.dir/build.make CMakeFiles/daytimeserver.dir/daytimeserver.cc.o
.PHONY : daytimeserver.cc.o

daytimeserver.i: daytimeserver.cc.i

.PHONY : daytimeserver.i

# target to preprocess a source file
daytimeserver.cc.i:
	$(MAKE) -f CMakeFiles/daytimeserver.dir/build.make CMakeFiles/daytimeserver.dir/daytimeserver.cc.i
.PHONY : daytimeserver.cc.i

daytimeserver.s: daytimeserver.cc.s

.PHONY : daytimeserver.s

# target to generate assembly for a file
daytimeserver.cc.s:
	$(MAKE) -f CMakeFiles/daytimeserver.dir/build.make CMakeFiles/daytimeserver.dir/daytimeserver.cc.s
.PHONY : daytimeserver.cc.s

echoclient.o: echoclient.cc.o

.PHONY : echoclient.o

# target to build an object file
echoclient.cc.o:
	$(MAKE) -f CMakeFiles/echoclient.dir/build.make CMakeFiles/echoclient.dir/echoclient.cc.o
.PHONY : echoclient.cc.o

echoclient.i: echoclient.cc.i

.PHONY : echoclient.i

# target to preprocess a source file
echoclient.cc.i:
	$(MAKE) -f CMakeFiles/echoclient.dir/build.make CMakeFiles/echoclient.dir/echoclient.cc.i
.PHONY : echoclient.cc.i

echoclient.s: echoclient.cc.s

.PHONY : echoclient.s

# target to generate assembly for a file
echoclient.cc.s:
	$(MAKE) -f CMakeFiles/echoclient.dir/build.make CMakeFiles/echoclient.dir/echoclient.cc.s
.PHONY : echoclient.cc.s

echoserver.o: echoserver.cc.o

.PHONY : echoserver.o

# target to build an object file
echoserver.cc.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/echoserver.cc.o
.PHONY : echoserver.cc.o

echoserver.i: echoserver.cc.i

.PHONY : echoserver.i

# target to preprocess a source file
echoserver.cc.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/echoserver.cc.i
.PHONY : echoserver.cc.i

echoserver.s: echoserver.cc.s

.PHONY : echoserver.s

# target to generate assembly for a file
echoserver.cc.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/echoserver.cc.s
.PHONY : echoserver.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/posix_time.dir/build.make CMakeFiles/posix_time.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/posix_time.dir/build.make CMakeFiles/posix_time.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/posix_time.dir/build.make CMakeFiles/posix_time.dir/main.cc.s
.PHONY : main.cc.s

multithread.o: multithread.cc.o

.PHONY : multithread.o

# target to build an object file
multithread.cc.o:
	$(MAKE) -f CMakeFiles/multithread.dir/build.make CMakeFiles/multithread.dir/multithread.cc.o
.PHONY : multithread.cc.o

multithread.i: multithread.cc.i

.PHONY : multithread.i

# target to preprocess a source file
multithread.cc.i:
	$(MAKE) -f CMakeFiles/multithread.dir/build.make CMakeFiles/multithread.dir/multithread.cc.i
.PHONY : multithread.cc.i

multithread.s: multithread.cc.s

.PHONY : multithread.s

# target to generate assembly for a file
multithread.cc.s:
	$(MAKE) -f CMakeFiles/multithread.dir/build.make CMakeFiles/multithread.dir/multithread.cc.s
.PHONY : multithread.cc.s

printer.o: printer.cc.o

.PHONY : printer.o

# target to build an object file
printer.cc.o:
	$(MAKE) -f CMakeFiles/printer.dir/build.make CMakeFiles/printer.dir/printer.cc.o
.PHONY : printer.cc.o

printer.i: printer.cc.i

.PHONY : printer.i

# target to preprocess a source file
printer.cc.i:
	$(MAKE) -f CMakeFiles/printer.dir/build.make CMakeFiles/printer.dir/printer.cc.i
.PHONY : printer.cc.i

printer.s: printer.cc.s

.PHONY : printer.s

# target to generate assembly for a file
printer.cc.s:
	$(MAKE) -f CMakeFiles/printer.dir/build.make CMakeFiles/printer.dir/printer.cc.s
.PHONY : printer.cc.s

test.o: test.cc.o

.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/test_1.dir/build.make CMakeFiles/test_1.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i

.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/test_1.dir/build.make CMakeFiles/test_1.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s

.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/test_1.dir/build.make CMakeFiles/test_1.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... daytime"
	@echo "... multithread"
	@echo "... bind"
	@echo "... posix_time"
	@echo "... test_1"
	@echo "... daytimeserver"
	@echo "... asyncdaytimeserver"
	@echo "... printer"
	@echo "... echoserver"
	@echo "... echoclient"
	@echo "... asyncdaytimeserver.o"
	@echo "... asyncdaytimeserver.i"
	@echo "... asyncdaytimeserver.s"
	@echo "... bind.o"
	@echo "... bind.i"
	@echo "... bind.s"
	@echo "... daytime.o"
	@echo "... daytime.i"
	@echo "... daytime.s"
	@echo "... daytimeserver.o"
	@echo "... daytimeserver.i"
	@echo "... daytimeserver.s"
	@echo "... echoclient.o"
	@echo "... echoclient.i"
	@echo "... echoclient.s"
	@echo "... echoserver.o"
	@echo "... echoserver.i"
	@echo "... echoserver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... multithread.o"
	@echo "... multithread.i"
	@echo "... multithread.s"
	@echo "... printer.o"
	@echo "... printer.i"
	@echo "... printer.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

